# Generated by Django 5.1.4 on 2025-02-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flight",
            old_name="destiantion",
            new_name="destination",
        ),
    ]
